cloudevents/sdk-javascript

- README.md
The README emitter example currently doesn't work because the word new is missing.
> Bug fix for example regarding emitting

- CHANGELOG.md
- README.md
- lib/specs/spec_0_3.js
- lib/utils/fun.js
- package.json
- test/bindings/http/receiver_strutured_0_3_test.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/fun_tests.js
- test/spec_0_3_tests.js
This PR has the intent to fix issue #33, by performing the special data handling described in the spec 0.3, [right here](https://github.com/cloudevents/spec/blob/v0.3/json-format.md#31-special-handling-of-the-data-attribute)
> To fix the 'data' special handling

- README.md
This commit removes the API documentation for the `fromString` Cloudevent
function as it does not seem to exist.
> Remove non-existing fromString from README API doc

- .travis.yml
This commit modifies the Travis-CI configuration so that the tests
are run for pull requests.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/51
> ci: run test suite for pull requests

- CHANGELOG.md
- lib/bindings/http/emitter_binary.js
- lib/bindings/http/emitter_structured.js
- test/http_binding_1.js
- v1/index.js
This commit modifies both of the 1.0 emitters so that they may
accept typed objects as a part of the configuration. When using
mTLS in Node, you need to provide an `Agent` to the underlying
HTTP handler. In this case, Axios will pass this object along to
Node.js when it is provided.
Note: This does not address the issue in 0.3 or below.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/48
> fix: support mTLS in 1.0 Binary and Structured emitters

- .travis.yml
- CHANGELOG.md
- lib/bindings/http/emitter_binary.js
- lib/specs/spec_0_2.js
- lib/specs/spec_0_3.js
- lib/specs/spec_1.js
- package-lock.json
- package.json
- test/http_binding_0_2.js
- test/http_binding_0_3.js
This commit updates all of the dependencies in package.json to
their most recent versions. It also removes dependencies that were
specified in package.json but not used - or only used in a
`require()` statement.
These changes have some ripple effects. Istanbul has not been
supported for some time, so it has been replaced with nyc.
The code coverage reporting tool from codacy has been updated
as well. This could not be tested without having the API token.
Finally, the CI job has been modified to run tests on Node.js
versions 10x and 12x. All older versions of Node.js are no longer
maintained.
Fixes: https://github.com/cloudevents/sdk-javascript/pull/50
> deps: update old and remove unused dependencies

- test/bindings/http/unmarshaller_0_3_tests.js
This commit updates the http unmarshaller tests to use the constants
available in `lib/bindings/http/constants.js`.
> test: use header constants in unmarshaller tests

- CHANGELOG.md
- CONTRIBUTING.md
- package-lock.json
- package.json
This commit adds the `standard-version` module for managing releases.
When running `npm run release` the following steps are taken.
1. Retreive the current version of your repository by looking at package.json.
2. Bump the version in package.json based on the commits.
3. Prepends to the CHANGELOG based on the commits (uses conventional-changelog under the hood).
4. Create a new commit including the package.json and updated CHANGELOG.
5. Create a new tag with the new version number.
This works best if all commits follow the Conventional Commits specification.
https://www.conventionalcommits.org/en/v1.0.0/
Fixes: https://github.com/cloudevents/sdk-javascript/issues/56
> chore: add standard-version and release script

- package.json
The code coverage publishing in package.json works fine on non-ubuntu systems.
However, in Ubuntu `/bin/sh` is symlinked to `/bin/dash` which doesn't support
everything supported by `/bin/bash` - specifically `-o pipefail`.
This commit changes the code coverage script to explicitly use `bash` instead.
> chore: fix CI code coverage publishing

- examples/express-ex/package.json
Related to #76 
Now it uses the same approach as TypeScript example: https://github.com/cloudevents/sdk-javascript/blob/master/examples/typescript-ex/package.json#L28
> fix: Fix Express example installation

- lib/formats/json/formatter.js
> feat: formatter.js es6

- README.md
This SDK doesn't support 0.1 or 0.2 anymore. Remove that reference from the README.
> docs: remove 0.1, 0.2 spec support from README

- .eslintrc
- index.js
- lib/formats/json/parser.js
- lib/specs/spec_1.js
- test/bindings/http/receiver_binary_0_3_tests.js
- test/bindings/http/receiver_binary_1_tests.js
- test/bindings/http/receiver_structured_0_3_test.js
- test/bindings/http/receiver_structured_1_test.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/formats/json/parser_test.js
- test/spec_0_3_tests.js
Enforce the use of `let` and `const` by using elsint rules.
When creating the eslint configuration, I had assumed that
`extends: eslint:recommended` would have covered this, but
apparently not!
Existing usage of `var` fixed with `npm run lint -- --fix`.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/97
> chore: update eslint rules to disallow var usage

- README.md
- examples/typescript-ex/src/index.ts
- index.js
- lib/bindings/http/receiver_binary.js
- lib/bindings/http/receiver_structured.js
- test/bindings/http/receiver_binary_0_3_tests.js
- test/bindings/http/receiver_binary_1_tests.js
- test/bindings/http/receiver_structured_1_test.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/http_binding_0_3.js
- test/http_binding_1.js
- test/spec_0_3_tests.js
- test/spec_1_tests.js
- v03/index.js
- v1/index.js
Uses the same capitalization for CloudEvents everywhere.
Fixes #100.
> refactor: use CloudEvents not cloudevents everywhere

- README.md
There's a link to 0.1 and some other links in the README that aren't specific to the Node SDK. Let's remove them.
> chore: remove note with bad link and non SDK docs

- README.md
We don't need to keep the repo structure in the main README of the docs. This won't be used by external developers and isn't really useful for those building the SDK.
> docs: remove repo structure docs

- README.md
This PR organizes the README header and makes incremental improvements to the README aimed at people skimming it for the first time.
- Reduce Badges to fit in one line
- Change project title
- Remove logo that isn't seen in other SDKs
- Remove TypeScript example from main README.
- Organize some headers to show code first
> docs: organize README badges and remove TS example

- lib/specs/spec_0_3.js
- lib/specs/spec_1.js
This commit updates the 0.1 and 0.3 sources to use the specversion
available in schema definitions.
> lib: use specversion from schema

- lib/bindings/http/emitter_binary.js
- lib/bindings/http/emitter_structured.js
- test/http_binding_1.js
- v1/index.js
This commit modifies both of the 1.0 emitters so that they may
accept typed objects as a part of the configuration. When using
mTLS in Node, you need to provide an `Agent` to the underlying
HTTP handler. In this case, Axios will pass this object along to
Node.js when it is provided.
Landed in: https://github.com/cloudevents/sdk-javascript/commit/3a063d72451d1156df8fe9c3499ef1e81e905060
Pull Request: https://github.com/cloudevents/sdk-javascript/pull/53
Fixes: https://github.com/cloudevents/sdk-javascript/issues/48
> fix: [backport] support mTLS in 1.0 Binary and Structured emitters

- lib/bindings/http/receiver_binary.js
- test/bindings/http/receiver_binary_0_3_tests.js
- test/bindings/http/receiver_binary_1_tests.js
The Knative Kafka event source does not include a `Content-Type` header when
sending binary events. The CE HTTP binding specification doesn't address how
a receiver should handle this situation.
This commit makes `application/json` the default.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/117
Ref: https://github.com/cloudevents/spec/issues/614
> fix: make application/json the default content type in binary mode

- index.js
- lib/bindings/http/http_receiver.js
- test/bindings/http/promiscuous_receiver_test.js
- test/bindings/http/receiver_structured_1_test.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/spec_0_3_tests.js
- test/spec_1_tests.js
Event receivers in the wild may not always know what version or mode an
incoming event is. Instead of requiring developers to inspect the headers
themselves, the SDK should provide an HTTP receiver that is capable of
figuring out what the version and mode (structured/binary) of an incoming
event is and handle it appropriately.
In determining the best way to expose this, I chose to modify the API a
little bit. Now, instead of `const CloudEvent = require('cloudevents-sdk');`
users need to destructure it.
```js
const { HTTPReceiver, CloudEvent } = require('cloudevents-sdk');
```
This change should not be backported to 1.x.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/93
> feat: expose a mode and version agnostic event receiver

- lib/bindings/http/unmarshaller.js
- test/bindings/http/unmarshaller_0_3_tests.js
This commit removes the unnecessary use of Promises in the 0.3 unmarshaller.
There was actually no asynchronous activity happening in that function, so
there was no need to deal with Promises, and as a result testing was made
much more difficult.
This is a breaking change.
Fixes: https://github.com/cloudevents/sdk-javascript/pull/95
> feat(unmarshaller)!: remove asynchronous 0.3 unmarshaller API

- test/bindings/http/receiver_binary_0_3_tests.js
- test/bindings/http/receiver_binary_1_tests.js
> test: use header constants in receiver tests

- lib/bindings/http/receiver_binary.js
- lib/bindings/http/receiver_binary_1.js
- test/bindings/http/promiscuous_receiver_test.js
The fix provided in https://github.com/cloudevents/sdk-javascript/pull/118
only included tests for `receiver.check()`, and the change in that
case was to add the `application/json` content type to the cleansed
headers if no type was specified.
However, `receiver.parse()` did not receive the benefit of this change. It
calls `this.check()` but then sanitizes the original headers again, and the
missing content-type was not re-inserted into the newly sanitized headers.
This commit, modifies the code so that `receiver.check()` does not insert
the content-type, but does allow the validation check to pass if no
content-type header exists. When `receiver.parse()` is called, and the
headers are sanitized again - and this time used to look up parser implementation,
the default `application/json` …
> fix: ensure binary events can handle no content-type header

- README.md
- examples/express-ex/README.md
- examples/express-ex/index.js
- examples/typescript-ex/src/index.ts
This commit modifies the README to show new API usage for the
`HTTPReceiver` and `CloudEvent` classes, and updates the examples
to use this as well.
Overall, the readme has been modified to look more like the sdk-go readme.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/128
> docs: update README and examples with new API

- lib/bindings/http/http_receiver.js
- test/bindings/http/promiscuous_receiver_test.js
This commit changes the event mode detection in `HTTPReceiver` so that it will
throw a TypeError if the event mode can't be detected per the spec.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/136
> fix: throw "no cloud event detected" if one can't be read

- CONTRIBUTING.md
- maintainer_guidelines.md
- pr_guidelines.md
* Added detailed instructions for outside contributors.
* Added tips for maintainers
* Documented branching strategy
Fixes: https://github.com/cloudevents/sdk-javascript/issues/85
Fixes: https://github.com/cloudevents/sdk-javascript/issues/72
> docs: add instructions and details to contributors guide

- lib/bindings/http/unmarshaller.js
This commit removes two unnecessary else clauses in unmarshaller.js, and
also extracts the throwing of TypeError of invalid content types into a
separate function to avoid some code duplication.
> lib: remove unnecessary else statements

- test/spec_0_3_tests.js
This commit removes the require of uuid from this test and uses a
hardcoded value for the 'id' constant instead.
The motivation for this is that the value for 'id' does not need to be
generated for each test run, and fewer requires helps readabilitly I
find.
> test: remove uuid require in spec_03_tests.js

- lib/bindings/http/http_receiver.js
This commit adds the '.js' suffix to the require of receiver_binary_0_3
to be consistent with the other requires statments in this file.
> lib: add .js suffix to receiver_binary_0_3

- lib/bindings/http/http_receiver.js
Currently, the mode variable in getMode is set to 'unknown' but this
will never get returned as the else clause will throw a TypeError if the
detected mode (from the passed-in headers) is not structured or binary.
This commit suggests simplifying the getMode function and removes the
mode variable.
> lib: remove mode variable from getMode

- test/spec_0_3_tests.js
> test: use constants in spec_03_tests.js

- lib/bindings/http/receiver_structured.js
- lib/bindings/http/receiver_structured_0_3.js
- lib/bindings/http/receiver_structured_1.js
This commit changes the setterByAttribute to be a map and tries to
reduce some code duplication and improve readability.
> lib: make setterByAttribute a Map

- lib/bindings/http/http_receiver.js
- lib/bindings/http/receiver_binary.js
- lib/bindings/http/receiver_binary_0_3.js
- lib/bindings/http/receiver_structured.js
- lib/bindings/http/unmarshaller.js
- lib/cloudevent.js
- lib/formats/json/parser.js
- lib/specs/spec_0_3.js
- lib/specs/spec_1.js
- lib/validation_error.js
- test/bindings/http/promiscuous_receiver_test.js
- test/bindings/http/receiver_binary_0_3_tests.js
- test/bindings/http/receiver_binary_1_tests.js
- test/bindings/http/receiver_structured_0_3_test.js
- test/bindings/http/receiver_structured_1_test.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/formats/json/parser_test.js
- test/spec_0_3_tests.js
- test/spec_1_tests.js
This change adds a `ValidationError` type, extending `Error`, which takes an optional array of strings as a second parameter.
> feat: add ValidationError type extending TypeError

- lib/bindings/http/receiver_binary_1.js
Signed-off-by: Helio Frota <00hf11@gmail.com>
> lib: removes unused array

- README.md
- index.js
- lib/bindings/http/emitter_binary.js
- lib/bindings/http/emitter_binary_0_3.js
- lib/bindings/http/emitter_binary_1.js
- lib/bindings/http/emitter_structured.js
- lib/bindings/http/http_emitter.js
- test/bindings/http/http_emitter_test.js
- test/bindings/http/receiver_structured_0_3_test.js
- test/bindings/http/receiver_structured_1_test.js
- test/http_binding_0_3.js
- test/http_binding_1.js
- test/sdk_test.js
- v03/index.js
- v1/index.js
This is a breaking change.
This commit exposes an HTTP based event emitter that simplifes the API.
To use it, simply import the SDK and start emitting. The default spec
version is 1.0, but you can use 0.3 by supplying that to the constructor.
By default, CloudEvents are emitted in binary mode, but this can be changed
by providing the "structured" parameter to the `emit()` function.
This commit also eliminates the version specific emitters and receivers
from the `v1` and `v03` exports, and eliminates the explicit usage of
versioned emitters from `lib/bindings/http`.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/124 
> feat!: expose a version agnostic event emitter

- lib/bindings/http/http_receiver.js
This commit removes the `version` variable from `getVersion` and updates the
code to use return statements to be consitent with other functions in
this file, like `getMode` and `accept`.
> lib: remove version variable from getVersion

- lib/utils/fun.js
This commit removes the 'result' variable form the utility function
asData. The motivation is to improve readability.
> lib: remove result variable from asData

- index.js
- lib/bindings/http/constants.js
- lib/bindings/http/http_receiver.js
- lib/bindings/http/unmarshaller.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/constants_test.js
- test/spec_0_3_tests.js
This commit pulls the constants up from the lib/bindings/http/constants.js
and exports them in the top level index.js. There are some elements of the API
where we expect users to provide constant values, and this makes it easier for
them to be sure the values they provide are what is expected.
I've also added two new constants: `BINARY` and `STRUCTURED`.
> lib: expose constants as a top-level export

- lib/bindings/http/constants.js
- lib/bindings/http/emitter_binary_0_3.js
- lib/bindings/http/receiver_binary_0_3.js
- test/bindings/http/unmarshaller_0_3_tests.js
- test/constants_test.js
> lib: correct name of CONTENT_ENCODING constant

- lib/bindings/http/emitter_binary.js
- lib/bindings/http/http_emitter.js
- lib/bindings/http/v03/emitter_binary_0_3.js
- lib/bindings/http/v1/emitter_binary_1.js
This commit turns the `headerByGetter` Object into a `Map` to reduces some
code duplication an hopefully improve readability a little.
> lib: make headerByGetter a Map

- lib/bindings/http/http_emitter.js
- test/bindings/http/http_emitter_test.js
Now, instead of requiring an instance of HTTPEmitter to retrieve the headers
for an event, you can get them this way:
```js
const headers = HTTPEmitter.headers(myCloudEvent);
```
Fixes: https://github.com/cloudevents/sdk-javascript/issues/178
> lib: make HTTPEmitter headers method a property of the class

- maintainer_guidelines.md
Fixes: https://github.com/cloudevents/sdk-javascript/issues/86
> docs: add maintainer guidelines for landing PRs

- maintainer_guidelines.md
- pr_guidelines.md
Signed-off-by: Doug Davis <dug@us.ibm.com>
> chore: minor typos in guidance docs

- .gitignore
- src/lib/bindings/http/emitter_binary.js
- src/lib/bindings/http/emitter_structured.js
- src/lib/bindings/http/receiver_binary.js
- src/lib/bindings/http/receiver_structured.js
- src/lib/bindings/http/v03/emitter_binary_0_3.js
- src/lib/bindings/http/v03/receiver_binary_0_3.js
- src/lib/bindings/http/v03/receiver_structured_0_3.js
- src/lib/bindings/http/v1/emitter_binary_1.js
- src/lib/bindings/http/v1/receiver_structured_1.js
- src/lib/bindings/http/validation/binary.js
- src/lib/bindings/http/validation/commons.js
- src/lib/bindings/http/validation/structured.js
- src/lib/cloudevent.ts
Even though `constants.js` will work just fine here, since that file is ultimately generated, having the `.js` extension in the `/src` tree confuses some tools - e.g. `ts-loader` for webpack.
> fix: fix references to constants - remove .js extension

- .gitignore
> fix: use /lib in gitignore so src/lib is not ignored

- README.md
Simplifies the README header. Let's make this repo really simple to use.
Fixes: #204
- We have a license file, GitHub/npm makes it obvious with various tooling.
- We're already on major version 2+, it's common for API versions and client versions to differ, no need to mention it.
> Simplify README.md Header

- package-lock.json
- package.json
- src/lib/bindings/http/http_emitter.ts
- src/lib/bindings/http/http_receiver.ts
- src/lib/cloudevent.ts
- test-ts/cloud_event_test.ts
- test-ts/http_emitter_test.ts
- test-ts/http_receiver_test.ts
- tsconfig.json
This commit modifies the existing TypeScript files with improved
(read: functional) typings for function parameters. This became an
issue when trying to use the module in an existing TypeScript module.
Tests for the TypeScript files have been moved to a new test folder
specifically for testing TypeScript usage via ts-node.
> fix: add correct types to improve usage in TypeScript projects

- src/lib/bindings/http/http_receiver.ts
The `HTTPReceiver` class' `accept()` method should not have a typescript
type designation of `{ specversion: string }` for the `body` parameter
because the event could be (and often is) in binary form, which means that
the `specversion` property won't be there.
This commit changes the method signature to:
`accept(headers: {}, body: {}) : CloudEvent`
> lib: remove specversion from the attributes in receiver.accept()

- src/lib/formats/base64.ts
- src/lib/formats/json/formatter.ts
- src/lib/formats/json/parser.ts
Uses `any` for now as many types are a bit whack with the hybrid ts/js repo.
> feat: ts formatter

- README.md
- examples/express-ex/README.md
> docs: Update references of specific versions to use Latest Supported.

- .github/workflows/api-docs.yaml
- package-lock.json
- package.json
- src/lib/formats/json/parser.ts
- tsconfig.json
Fixes: https://github.com/cloudevents/sdk-javascript/issues/212
> docs: generate api documentation as a GitHub workflow

- package.json
Adds TypeScript types to npm module.
See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Fixes: #213
> feat: add types to package.json

- examples/express-ex/index.js
- examples/express-ex/package.json
- examples/typescript-ex/README.md
- examples/typescript-ex/package.json
- examples/typescript-ex/prettier.config.js
- examples/typescript-ex/src/index.ts
- examples/typescript-ex/tsconfig.json
This PR starts to update the examples in `examples` to use the latest released cloudevents-sdk(which is 2.x atm)
fixes #187
> Update examples to latest(2.x) sdk

- src/lib/cloudevent.ts
- src/lib/extensions.ts
- src/lib/v03/index.ts
- src/lib/v1/index.ts
- test-ts/cloud_event_test.ts
* This allows someone to pass an extension/extensions into the CloudEvent contructor when creating a CloudEvent.
fixes #209
> feat: pass extension into the constructor.

- src/lib/cloudevent.ts
I'm usually a sublime text users,  so i didn't catch this until i opened the code in vscode,  but this adds the return types to the extension methods
> chore: adds the return type for the extension methods

- src/lib/bindings/http/validation/structured.js
> fix: parse method mutating its input

- .github/workflows/stale.yml
Open issues and pull requests should be closed by a human who has considered
the issue/pr and made a choice based on the content of the issue/pr and the
state of the repository.
What this means in practice is that some issues will stay open for a long
time, even if they are stale. They may be open because it really is something
that will be considered for future work. Periodic issue triage should be
done by the maintainers, and if an issue _should_ be closed - for example,
the issue is no longer relevant - then a maintainer can close it.
> chore(actions): don't auto-close stale issues and pull requests

- src/transport/receiver.ts
- test/http_receiver_test.ts
Even though the underlying structured and binary receivers already sanitize
the headers, this needs to be done at the receiver.accept() level since
the headers are inspected there to determine what mode the event is being
sent as.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/237
> fix: ensure that the HTTP receiver sanitizes headers in accept()

- .github/workflows/stale.yml
This is the first version that actually avoids closing stale issues if `days-before-close < 0`.
> chore: bump GH stale action to v3

- src/event/cloudevent.ts
- src/event/v03/cloudevent.ts
- src/event/v1/cloudevent.ts
- test/integration/cloud_event_test.ts
- test/integration/http_binding_03.ts
- test/integration/http_binding_1.ts
- test/integration/spec_03_tests.ts
- test/integration/spec_1_tests.ts
During the creation of a CloudEvent,  the validate method is now called.  The object is also frozen to make it read-only.
A new method `cloneWith` has been added which can be used to add/update attributes such as extensions and will return a new Cloud Event Object
fixes #233 
related #29 
> Validate a Cloud Event on creation and make it read only with a method to augment it

- README.md
This updates the readme now that cloud events will be read-only.  
Also mentions the `cloneWith` method
> Update readme that mentions CloudEvents are read-only now

- src/event/cloudevent.ts
- test/integration/cloud_event_test.ts
- test/integration/receiver_structured_1_test.ts
- test/integration/spec_1_tests.ts
This validates the extension names based on the spec, https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention
fixes #228 
> Validate extension names

- README.md
This commit separates the spec compliance table in the README.md file
into three: the core spec, event formats, and transport protocols.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/166
> docs: clean up spec compliance table on README.md

- src/transport/http/binary_receiver.ts
- src/transport/http/structured_receiver.ts
- src/transport/receiver.ts
- test/integration/http_receiver_test.ts
- test/integration/receiver_binary_03_tests.ts
- test/integration/receiver_binary_1_tests.ts
This commit modifies the HTTP receivers/parsers to allow for the incoming body
of an HTTP request to be empty if the event message is sent using the binary
mode. In structured mode, a `ValidationError` will still be thrown, since the
entire event must be encoded in the HTTP body.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/258
> fix: do not require an HTTP body on incoming binary messages

- src/transport/receiver.ts
- test/conformance/steps.ts
- test/integration/http_receiver_test.ts
Note that I did not add a third `Protocol` parameter to `Receiver.accept` since
that would not currently be used. It's non-breaking to add a third parameter
in the future once additional protocols are supported.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/266
Fixes: https://github.com/cloudevents/sdk-javascript/issues/261
BREAKING CHANGE
> lib: change Receiver#accept() to be static Receiver.accept

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull-request-template.md
- .vscode/tasks.json
This commit adds templates for GitHub issues and PRs, and a configuration
file for VSCode to enable build and test tasks in the IDE.
> chore: add vscode task JSON and GitHub issue/pr templates

- src/event/cloudevent.ts
- src/event/validation.ts
- test/integration/http_emitter_test.ts
- test/integration/spec_1_tests.ts
This validates the value of the cloud event extension based on the spec, https://github.com/cloudevents/spec/blob/master/spec.md#type-system
I still need to add a check for the value being a URI
fixes #229
> lib: validate extension values

- src/event/schemas.ts
- test/integration/cloud_event_test.ts
The schema incorrectly limits data values to only object and string. This is
incorrect, since JSON can be an array, boolean, null or a single number as well.
This changes the schemas for both 0.3 and 1.0 events and adds test cases.
- Fixes: https://github.com/cloudevents/sdk-javascript/issues/280
- Version: 3.0.0
> fix: ensure that event data can be an array, number, boolean or null

- README.md
-  Updates the Readme with the correct usage of Receiver
> chore: Update readme with correct Receiver usage

- src/transport/http/binary_receiver.ts
- src/transport/http/structured_receiver.ts
- test/integration/receiver_binary_03_tests.ts
- test/integration/receiver_structured_0_3_test.ts
Parse incoming data as JSON for an event with `datacontentencoding` set to "base64"
and a content type of application/json or application/cloudevents+json.
The 0.3 specification states that `datacontentencoding` may be set to base64.
If an incoming event arrives over HTTP with this value set, and the content type
is either application/json or application/cloudevents+json, then we should ensure
that the data is decoded and parsed, and the `datacontentencoding` property is
removed.
- Fixes: https://github.com/cloudevents/sdk-javascript/issues/284
- See: https://github.com/cloudevents/sdk-javascript/pull/282
- Version: 3.0.0 (spec version 0.3)
> fix: ensure that data encoded as base64 is parsed as an object

- examples/express-ex/README.md
- examples/express-ex/index.js
- examples/express-ex/package.json
- examples/payload/v03/structured-event-1.json
- examples/payload/v03/structured-event-2.json
- examples/payload/v1/structured-event-1.json
- examples/payload/v1/structured-event-2.json
- examples/typescript-ex/package.json
- examples/typescript-ex/src/index.ts
- examples/websocket/README.md
- examples/websocket/client.js
- examples/websocket/index.html
- examples/websocket/package.json
- examples/websocket/server.js
- This PR updates the examples to use the latest cloudevents module(3.x)
All the examples work except one curl statement in the express example that is being addressed by #284 and since we are using the `~` those changes will get picked up once a new patch version is released, automatically
- Fixes Issue #249 
- Version:
> chore: Update examples to use latest sdk changes

- README.md
- package.json
- postinstall/message.js
Since we have recently changed the name of this module to 'cloudevents', users
may not be aware that version 2.0.2 is out of date, since it won't automatically
be upgraded on `npm install`.
This commit adds a postinstall script to warn users of this fact, and adds a
bold, top-level warning to the README.
- Fixes: https://github.com/cloudevents/sdk-javascript/issues/291
- Version: 2.x
> chore(release): add postinstall script to warn users of name change

- src/index.ts
- test/integration/constants_test.ts
This change exposes the`Constants` from the "index" so a user no longer has to path into the dist folder.  I believe this was the original way to do it before the Typescript re-write
- Fixes Issue #298
- Version: 3.x
> lib(Constants): expose constants in a more intuitive way

- src/transport/http/binary_emitter.ts
- test/integration/http_emitter_test.ts
This changes the header of the emitted Binary Event to be the correct header
- Fixes Issue #301
- Version: 3.x
> fix: Add Correct Headers to emitted Binary Event

- test/integration/http_emitter_test.ts
This updates some the tests that are promise based to return the promise so mocha fails correctly if a test fails
Link to the CI run that proves that it fails, https://github.com/cloudevents/sdk-javascript/runs/954405480?check_suite_focus=true#step:6:559
- Fixes Issue #303 
- Version: 3.x
> chore:  fix promise tests to break the build when they fail

- package.json
This adds a postcommit hook to our release script to amend the commit with the signoff.
related to #304 
- Version:3.x
> chore: update the release script to signoff the commit

- RELEASE_GUIDELINES.md
This is the start of a release guidelines for maintainers.
I think i have everything here.  There is one TODO, asking if we should have a specified time after the last "+1" from other maintainers.
Outstanding questions:
*  does the current release script also sign and adds the "signed-off by" thing 
* Should we mention something on publishing docs here
* Should we add that we should create a "release" on github
- Fixes Issue #304
> docs: Release Guidelines

- README.md
- examples/express-ex/index.js
Improves the README examples for receiving CloudEvents.
- Don't define unused imports
- Make `req` and `res` defined.
- Small JS syntax changes
Fixes: https://github.com/cloudevents/sdk-javascript/issues/308
> docs: improve readme receiver example

- README.md
Wait until https://github.com/cloudevents/spec/pull/663 is resolved.
However, look over the wording and once we get that right I'll open similar PRs in other SDK repos
Signed-off-by: Doug Davis <dug@us.ibm.com>
> Add ref to CoC and other things

- src/event/cloudevent.ts
- src/event/spec.ts
- src/transport/http/binary_receiver.ts
- src/transport/http/structured_receiver.ts
- Simplify CE validation
- Fixes part of https://github.com/cloudevents/sdk-javascript/issues/273
> refactor: validate cloudevent version agnostic

- test/integration/cloud_event_test.ts
- Implement pending `CloudEvent` tests
- Fixes Issue https://github.com/cloudevents/sdk-javascript/issues/232
- Version: 3.1.0
This commit implements 4 of the 6 pending tests that were not completed
during the TypeScript rewrite. The two tests that were not implemented
were (one for each of v1 and v03):
```
it("returns a JSON string even if format is invalid");
```
I don't really know what that's supposed to be/mean, so I removed them.
> test: implement pending tests leftover from TS rewrite

- .github/pull-request-template.md
- .github/workflows/nodejs-ci-action.yml
- CONTRIBUTING.md
- README.md
- RELEASE_GUIDELINES.md
- maintainer_guidelines.md
- pr_guidelines.md
This updates the references in our Guides on GH Actions to use the `main` branch
There might be some formatting changes that are in here which happened when i saved in VSCode
> chore: Update references of master to main

- README.md
This updates the support specification headers with the correct links to their respective versions
There was also a stray `HTTPReceiver` in the readme examples that i took care of here
fixes #320
> chore: Update README with correct links for the support specification versions

- src/event/cloudevent.ts
- src/event/interfaces.ts
- src/event/schemas.ts
- src/event/spec.ts
- src/message/http/headers.ts
- src/parsers.ts
- test/integration/cloud_event_test.ts
- test/integration/http_binding_03.ts
- test/integration/http_binding_1.ts
- test/integration/http_emitter_test.ts
- test/integration/message_test.ts
- test/integration/spec_03_tests.ts
- test/integration/spec_1_tests.ts
- Change CloudEvent's time property to be only a string
- Remove all special handling of the time property in getters/setters
- Ensure that `event.time` always produces the value provided in the constructor
- Add validation logic so that `new Date().toString()` works with event attribute validation
- Improve the `DateParser` which processes an incoming binary event Message's `ce-time` header and `time` property for a structured event `Message`.
Previously, the event's `time` property could be either a string or a date.
this commit modifies that to ensure that the object can only be created with
a timestamp in string format. As long as the string is a valid date, that
can be parsed by `new Date(Date.parse(str))` then whenever the event is
serialized as JSON, the `time` attribute will be …
> src(event)!: make the event's time property only a string

- examples/express-ex/index.js
- examples/express-ex/package.json
Replaces body parser with standard express body-parse module
-
-
-
- Fixes Issue #
- Version:
> chore(example): Replaced body parser with express JSON parser

- src/event/cloudevent.ts
- src/event/validation.ts
- src/message/http/headers.ts
- src/message/http/index.ts
- test/integration/cloud_event_test.ts
- test/integration/message_test.ts
- add a second, optional, boolean parameter called `strict` to `CloudEvent` constructor, defaulting to `true`.
- add a second, optional, boolean parameter  called `strict` to `CloudEvent.cloneWith()` defaulting to `true`
- skip all validation steps if `strict` is false
- add tests for these changes 
This commit adds a second, optional boolean parameter to the `CloudEvent`
constructor. When `false` is provided, the event constructor will not
perform validation of the event properties, values and extension names.
As I am writing this, I wonder if it will be less error prone to default to `false`
and call the parameter `looseValidation`. 
- Fixes: https://github.com/cloudevents/sdk-javascript/issues/325
- Version: 3.1.0
> feat: add a constructor parameter for loose validation

- README.md
This commit changes the README to include all currently active
contributors to and the originator of the repository.
> docs: update README with maintainer names

- .github/workflows/release-please.yml
This adds the release-please GH action to automate our release process
~~Creating as a Draft since the changelog creation is still missing the full list of types~~
Also need to update the current release document with this new change, which can come in another issue if this works good
I've added a PR for the changelog creation, https://github.com/googleapis/release-please/pull/538
update(9/8/2020):  The above PR has been merged into release-please,  now i just need to create the PR against the GH action
update 2 (9/8/2020):  PR for the GH Action, https://github.com/GoogleCloudPlatform/release-please-action/pull/64
- Fixes Issue #312 
- Version:
> chore: add an automated GH action for releases

- README.md
Removes `Emitter` and `Receiver`, replacing them with `Message` and `HTTP.toEvent()`.
> docs: update README with latest API changes

- src/constants.ts
- src/event/cloudevent.ts
- src/message/http/index.ts
- src/message/index.ts
- src/parsers.ts
- test/integration/emitter_factory_test.ts
- test/integration/message_test.ts
- extend Node.js `IncomingHttpHeaders` in our `Headers` type
Changes the `Headers` type to make it more compatible with Node.js TypeScript projects.
- Fixes: https://github.com/cloudevents/sdk-javascript/issues/340
- Version:
> fix: extend Node.js IncomingHttpHeaders in our Headers type

- src/event/cloudevent.ts
This commit changes the messages produced when validating extension names and
values, including the offending name or value in the message, and including
text from the CloudEvent specification, or a link to the type system.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/364
> fix: improve error messages when validating extensions

- API_TRANSITION_GUIDE.md
- README.md
This adds a guide to show the transition of the deprecated API's of 3.2.0 .
We can also use this for future deprecations
fixes #360
> Deprecated API transition guide.

- examples/typescript-ex/package.json
- examples/typescript-ex/src/index.ts
- package-lock.json
- package.json
- src/transport/emitter.ts
This change modifies Emitter so that it does not directly extend the Node.js
EventEmitter class. Instead, it holds a singleton instance of an EventEmitter
but is not an instance of EventEmitter itself.
This commit also updates the typescript example to use a modern version of
@types/node and typescript.
Finally there are a few minor formatting changes picked up by eslint.
@loopingz if you have a chance to review this, that would be great. Thanks!
Fixes: https://github.com/cloudevents/sdk-javascript/issues/385
> fix: Emitter should not extend EventEmitter

- test/integration/cloud_event_test.ts
See: https://github.com/cloudevents/sdk-javascript/issues/380
> test: add a test for extension names with capital letters

- src/message/http/index.ts
- test/integration/message_test.ts
The `HTTP.isEvent()` and `HTTP.toEvent()` functions both had some validation
code that violated the principle of loose validation when receiving an
event over HTTP. As discussed, the validation should be managed by the
receiver in this case with `event.validate()`
> fix: ensure loose validation for isEvent and toEvent

- package.json
- tsconfig.json
Fixes: https://github.com/cloudevents/sdk-javascript/issues/392
This commit also removes the external doc theme, since the new version
generates decent looking docs.
After this lands, docs should be published.
> docs: fix 'npm run generate-docs'

- src/transport/emitter.ts
- test/integration/emitter_factory_test.ts
Fixes: https://github.com/cloudevents/sdk-javascript/issues/391
> fix: defaults properly handled for emitterFor()

- README.md
For some reason they had never been changed from @fabiojose
Fixes: https://github.com/cloudevents/sdk-javascript/issues/400
> doc: fix README.md coverage/quality badge links

- package-lock.json
- package.json
Now that we are using release-please, this is not necessary.
Closes: https://github.com/cloudevents/sdk-javascript/pull/393
> chore: remove standard-version

- CHANGELOG.md
- package-lock.json
- package.json
Also fixes a few minor linting issues from CHANGELOG.md.
> chore: add markdown linter

- .remarkrc
- package.json
This way Codacy will use our configuration instead of its own.
> chore: externalize remark-lint config

- README.md
Update the codacy badges to point at the new org.
Codacy originally had ad hoc organizations that were not connected to GitHub orgs. They are deprecating these in favor of Codacy orgs that mirror GitHub orgs. This change modifies the codacy badges in README.md so that they point to this new org. `CODACY_TOKEN` has been updated in this repository's settings so that all new code coverage reports will be pushed to the new org.
> chore: update codacy badges

- package-lock.json
- src/parsers.ts
- test/integration/parser_test.ts
A simple string is considered valid JSON. However, our parsers do
not accept that unless the string has quotation marks. This commit
modifies the parser to look for strings declared as application/json
which do not begin with '[' '{' or '"' and surrounds them with
quotes.
> src: be more forgiving parsing JSON as a string

- src/event/spec.ts
- src/event/validation.ts
- src/message/http/index.ts
- test/integration/message_test.ts
Also fixes the case where UPPERCASED extension names were silently changed
to lowercase and then set as undefined. Even though uppercased extension
names are invalid, we should still accept them in incoming messsages and
only throw when validating the event.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/380
> fix: throw on validation if extensions are improperly named

- .github/workflows/nodejs-ci-action.yml
This removes Node 10 from the CI since it is no longer supported.
This commit i used will only create a patch release,  but we might consider a major version bump for getting rid of a node version
> Remove node 10 from ci

- src/event/schemas.ts
- test/integration/cloud_event_test.ts
Fixes: https://github.com/cloudevents/sdk-javascript/issues/383
> fix: ensure source property has min length of 1

- src/event/cloudevent.ts
- test/integration/cloud_event_test.ts
Add better native logging to the `CloudEvent` class.
Logging a `CloudEvent` should call the `toString` of the `CloudEvent`.
Fixes https://github.com/cloudevents/sdk-javascript/issues/432
> feat: add native logging with headers and body to CloudEvent

- test/integration/message_test.ts
Simply adds an explicit test for a CE with data in `text/plain` format.
> chore: add test for text/plain data

- package-lock.json
- src/message/http/headers.ts
- test/integration/message_test.ts
The parser for HTTP binary made the assumption that if there was no `content-type`
header in the incoming message, it should inject `application/json`. Discussion
about the rationale for this is in https://github.com/cloudevents/sdk-javascript/issues/441.
This commit removes that injection and adds a test to ensure the bytes are not parsed, but just passed along untouched.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/441
> fix: do not assume an empty content-type header is JSON

- src/event/cloudevent.ts
- src/event/interfaces.ts
- src/event/spec.ts
- src/event/validation.ts
- src/message/http/headers.ts
- src/message/http/index.ts
- src/message/index.ts
- src/transport/emitter.ts
- test/integration/cloud_event_test.ts
- test/integration/message_test.ts
- test/integration/spec_1_tests.ts
Instead of using a big union of types, use a generic type for event data.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/445
> feat: use generic type for CloudEvent data

- README.md
- package-lock.json
- src/constants.ts
- src/message/http/index.ts
- src/message/index.ts
- test/integration/batch_test.ts
- test/integration/message_test.ts
This is experimental and still a work in progress. Would be interested in thoughts folks have on this - esp things like `HTTP.toEvent(): CloudEvent | CloudEvent[]`. The modifications were pretty simple in order to support batch mode, in my opinion. But it might have made some usage clunky, such as that. Marked as a WiP so I can add more tests and the overall design/direction can be hashed out first (if this doesn't look quite right).
/cc @cloudevents/sdk-javascript-maintainers 
Fixes: https://github.com/cloudevents/sdk-javascript/issues/440 (eventually)
> feat: add batch mode

- src/event/cloudevent.ts
- src/message/http/headers.ts
- src/message/http/index.ts
- src/message/index.ts
- test/integration/sdk_test.ts
This change modifies the protocol binding interfaces such as `Binding`, `Serializer` and the `cloneWith()` methods to use the `CloudEventV1` interface instead of the implementation class `CloudEvent`. This should make extending the interfaces simpler as using interfaces decouples Specification Extensions for relying on the concrete `CloudEvent` class. This work has grown out of efforts around the implementation of a second transport interface, Kafka.
See: https://github.com/cloudevents/sdk-javascript/pull/455/
In addition, this PR includes:
- The addition of a generic type to the `Message` interface, defaulting to `string`
- Some minor clean up involving what is exported from the `message/http` modules. Now, instead of exporting the entire implementation, only the `HTTP` binding …
> chore(refactor): prefer interfaces over concrete classes

- README.md
- src/index.ts
- src/message/index.ts
- src/message/mqtt/index.ts
- test/integration/mqtt_tests.ts
Add MQTT as a `Message` format.
This commit adds `MQTT` to the supported transport protocols by adding a `Binding` and the `MQTTMessage<T>` type, extending the base `Message` type, adding the MQTT fields for `payload`, `PUBLISH` and `User Properties`. The `payload` field directly maps to `Message#body`, while `User Properties` roughly maps to `Message#headers`, even though the properties here are not formatted with a `ce-` prefix like other transport protocols. This is per the spec. See: https://github.com/cloudevents/spec/blob/v1.0.1/mqtt-protocol-binding.md. The `PUBLISH` property is there primarily to support the `"Content type"` and perhaps should be typed better. Feedback welcome.
> feat: add MQTT transport messaging

- README.md
Fixes: #198 
Added some examples of the `CloudEvent` class usage.
@lance the `Event` type doesn't seem to be exported in the latest `cloudevents` package, so I didn't add that example.
Do let me know if you want any more changes 👍
> docs: add TS examples for CloudEvent usage

- package-lock.json
- package.json
- src/message/http/index.ts
- webpack.config.js
Previously, we were only checking for a single typed array, `UInt32Array` but that's not quite broad enough, since binary data can exist in various forms. This means of checking for binary data, using `types.isTypedArray` is not foolproof, but is better than previous, as the previous implementation would not recognize a PNG file read from disk via `fs.readFileSync` as binary data. Now it will.
> fix: improve binary data detection in HTTP transport

- src/index.ts
- src/message/kafka/index.ts
- src/message/mqtt/index.ts
- tsconfig.json
This setting ensures the module can be used in projects where the workflow
includes type checking and transpilation as two separate steps.
See: https://ncjamieson.com/dont-export-const-enums/
Fixes: https://github.com/cloudevents/sdk-javascript/issues/456
> fix: use `isolatedModules: true` in tsconfig.json

- RELEASE_GUIDELINES.md
It has been out of date since we switched to using release-please
for our release automation.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/474
> chore: update the release documentation

- README.md
This commit modifies the structure of the README.md to add a markdown
heading. This change is motiviated by the CLO tool provided by CNCF.
This repository is failing a check for maintainers as you can see on
the dashboard:
https://clomonitor.io/projects/cloudevents/cloudevents#sdk-javascript
Documentation for this change can be found here:
https://github.com/cncf/clomonitor/blob/main/docs/checks.md#maintainers
> doc: update maintainers in README.md

- package.json
Adds a convenience npm script that allows you to run only a single test
file at a time. Example usage:
```
sdk-javascript on  lance/update-deps-package-json [!?] is 📦 v5.3.2 via  v16.14.0
❯ npm run test:one
> cloudevents@5.3.2 test:one
> mocha --require ts-node/register
Error: No test files found
sdk-javascript on  lance/update-deps-package-json [!?] is 📦 v5.3.2 via  v16.14.0
❯ npm run test:one -- ./test/integration/batch_test.ts
> cloudevents@5.3.2 test:one
> mocha --require ts-node/register "./test/integration/batch_test.ts"
A batched CloudEvent message over HTTP
✔ Can be created with a typed Message
A batched CloudEvent message over Kafka
✔ Can be created with a typed Message
2 passing (5ms)
sdk-javascript on  lance/update-deps-package-json [!?] is 📦 v5.3.2 via  v16.14.0
``` …
> chore: add an npm test:once script

- package-lock.json
- package.json
- src/index.ts
- src/transport/http/index.ts
- test/integration/emitter_factory_test.ts
- webpack.config.js
This commit adds a base HTTP emitter that can be used to send events over HTTP without requiring any additional dependencies. It uses the Node.js builtin HTTP module instead of a dependency on axios/got/whatever. I have also eliminated the `axiosEmitter` in the desire to eliminate the axios dependency. I've done this as a single commit, so it can be reverted if folks prefer to keep it.
~~Also, before landing this, I would like to add HTTPS support.~~ Done
> feat!: add http transport and remove axios

- README.md
In addition to adding a simple example, I changed the `Emitter` singleton example to use this, as it's much simpler than the axios implementation.
> docs: update readme to include http builtin transport

- package-lock.json
- package.json
In this PR https://github.com/cloudevents/sdk-javascript/pull/471/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R128
it was not noticed that the addition of `ajv-formats` to devDependencies
is insufficient. Unfortunately, users of v6.0.0 will receive an error when
using the module, unless they explicitly install `ajv-formats` in their
project. This commit fixes that, and should result in an immediate release
of version 6.0.1.
> chore: update dependencies to inlude ajv-formats

- src/message/http/headers.ts
- test/integration/message_test.ts
CloudEvent objects may include extensions that have a defined key and a
`false` value. This change ensures that HTTP messages for CloudEvents
containing these extension values include the appropriate headers.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/492
> fix: HTTP headers for extensions with false values

- src/event/cloudevent.ts
- src/event/validation.ts
- test/integration/spec_1_tests.ts
Previously we only considered `Uint32Array` binary data. This was an oversight. This fixes that issue.
Fixes: https://github.com/cloudevents/sdk-javascript/issues/491
> fix: allow `TypedArray` for binary data

- src/event/spec.ts
- test/integration/kafka_tests.ts
- test/integration/message_test.ts
- test/integration/mqtt_tests.ts
- test/integration/spec_1_tests.ts
Fixes: https://github.com/cloudevents/sdk-javascript/issues/500
Adds a regular expression check to the attribute name validation code to
ensure that attribute names only use a-z0-9 (except for `data_base64`,
which apparently is an exception to the rule.
> fix: improve validation on extension attribute

- package-lock.json
- package.json
Duplicates https://github.com/cloudevents/sdk-javascript/pull/510
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
> chore: bump mocha to 10.1.0

- .gitignore
- examples/express-ex/index.js
- src/event/cloudevent.ts
- src/event/validation.ts
- src/message/mqtt/index.ts
- test/integration/cloud_event_test.ts
- test/integration/mqtt_tests.ts
- test/integration/spec_1_tests.ts
* CloudEvent class:
* Make data field immutable like the other fields in the class
* Make data field enumerable via `Object.keys()` and `Object.entries()`
* toJSON() does not return a `data` field anymore if `data_base64` is set to comply with the JSON format spec 3.1.1 `Out of this follows that the presence of the data and data_base64 members is mutually exclusive in a JSON serialized CloudEvent.`
Fixes https://github.com/cloudevents/sdk-javascript/issues/515
> fix: Make CloudEvent data field immutable and enumerable

- package-lock.json
- package.json
- webpack.config.js
Adds `process` plugin for webpack 5 and greater.
fixes #525
see https://github.com/browserify/node-util/issues/57#issuecomment-764436352 for the fix
> fix: add `process` plugin for browser compatibility

- .github/workflows/nodejs-ci-action.yml
- README.md
> Update CI action to node 18.x

- package-lock.json
- package.json
Currently, to run the tests successfully, `npm run build` needs to be run first in order to `ajv compile` the schema.  We started to run into this when we added this library to the test suite that runs these tests on RHEL and Fedora platforms in our node.js container.
see https://github.com/sclorg/s2i-nodejs-container/pull/384
error for reference:
```
TSError: ⨯ Unable to compile TypeScript:
src/event/spec.ts:10:22 - error TS2307: Cannot find module '../schema/v1' or its corresponding type declarations.
10 import validate from "../schema/v1";
~~~~~~~~~~~~~~
at createTSError (/Users/lholmqui/develop/cloudevents/sdk-javascript/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/Users/lholmqui/develop/cloudevents/sdk-javascript/node_modules/ts-node/src/index.ts:863:19)
at getOutput …
```
> chore: add the build script to the pretest script.

- package-lock.json
- package.json
Update Node version to 20.0.0
Fixes: https://github.com/cloudevents/sdk-javascript/issues/540
> 540 fix node version

- .github/workflows/release-please.yml
Older versions of release-please-action are deprecated and no longer work.
/cc @lholmquist
> chore: fix release-please-action

- package-lock.json
- package.json
Closes: https://github.com/cloudevents/sdk-javascript/pull/536
Closes: https://github.com/cloudevents/sdk-javascript/pull/535
> chore: bumps webpack to 5.76.0

- .github/workflows/release-please.yml
This adds another step to our release-please workflow that will automatically publish to npm when the release PR is merged
the CLOUDEVENTS_PUBLISH token has also been created
> chore: add publish automation

- README.md
This just removes the mention of the old node versions from the readme
> chore: remove old Node versions from the readme

- package.json
Allow Node 20.x
Now you allow only Node 20.0.0, let's make it compatible with all Node 20.x.x versions.
> chore: Update compatible node version

- .github/workflows/release-please.yml
The id of release was left out, so the checks to see if there needs to be a publish were being skipped
see https://github.com/cloudevents/sdk-javascript/actions/runs/5133682126/jobs/9236610689
> chore: fix the release-please automation script.

- .github/workflows/publish-to-npm.yml
- .github/workflows/release-please.yml
* This also splits the GH release and npm publish workflows
> chore: add the provenance flag when publishing to npm

- .github/workflows/api-docs.yaml
The github action that generates the documentation fails currently due to the fact that it's expecting the generated schema to exist, but it does not exist unless it's explicitly built.
This commit adds `npm run build:schema` to the workflow action.
> chore: add `npm run build:schema` to the doc generation action

- .github/workflows/release-please.yml
- package-lock.json
Modifies the release-please github action to add a "Signed-Off-By" line at the end of the commit, placating DCO.
@lholmquist I used your signoff since the release-please action seems to make the commits as you.
> chore: modify release-please to use Signed-Off-By on commits

- src/event/cloudevent.ts
- src/event/spec.ts
- src/index.ts
- src/message/http/headers.ts
- src/message/http/index.ts
- test/integration/cloud_event_test.ts
- test/integration/kafka_tests.ts
- test/integration/message_test.ts
- test/integration/mqtt_tests.ts
- test/integration/sdk_test.ts
- test/integration/spec_1_tests.ts
TypeScript does not consider enum values equivalent, even if the string representation is the same. So, when a module imports `cloudevents` and also has a dependency on another module which also has a dependency on `cloudevents` this can cause conflicts where the `CloudEvent.version` attribute is not considered equal when, in fact, it is.
Changing the `enum` to a string is pretty straightforward, but should be considered a breaking change since TypeScript dependents will potentially fail the build with a change like this.
See: https://github.com/knative/func/pull/1873#issuecomment-1640866356
Fixes: https://github.com/cloudevents/sdk-javascript/issues/323
> BREAKING CHANGE: use string instead of enum for `Version`

- README.md
The checkmarks in the table almost seemed disabled with dark theme of github readme. I think :white_check_mark: was more visible and obvious while going through readme.
> chore: updated check mark symbol to show some green checkboxes

- .github/workflows/api-docs.yaml
- .github/workflows/nodejs-ci-action.yml
- .github/workflows/publish-to-npm.yml
- package.json
Add compatibility for released LTS Node 22
Move some Github actions to their latest versions
> fix: allow Node 22 LTS and use it by default

- src/event/cloudevent.ts
- test/integration/cloud_event_test.ts
From the spec, the requirement for the length of attribute names is only a `SHOULD`, not a `MUST`. Currently, if the length is over 20 then the sdk throws an error, which I believe is incorrect because the length requirement is not a `MUST`.
- When an event attribute has a name lonoger than 2o characters, the SDK does not throw an error anymore
> fix: creating an event does not error when the event attribute name is too long

- .github/workflows/nodejs-ci-action.yml
- package-lock.json
- package.json
Node 16 has been EOL for a while now and it is time to remove it as a supported version.
I've tag this as a breaking change
> feat!: remove node 16
