cloudevents/sdk-javascript

- package.json
Signed-off-by: Fabio José <fabiojose@gmail.com>
> Fix the package name

- lib/bindings/http/binary_0_1.js
- lib/bindings/http/binary_0_2.js
- lib/bindings/http/structured_0_1.js
- lib/bindings/http/structured_0_2.js
Changed content type and made optional parameters optional as detailed in the cloudevents spec.
> Change binary http bindings to adhere to spec

- lib/bindings/http/constants.js
- lib/bindings/http/receiver_binary_0_2.js
- lib/bindings/http/unmarshaller_0_2.js
- test/bindings/http/receiver_binary_0_2_tests.js
https://github.com/cloudevents/sdk-javascript/issues/25
Signed-off-by: Jingwen Peng <pengsrc@outlook.com>
> Support receiving "application/octet-stream" content in binary transport mode

- README.md
> Fix typo in "What we can do" table

- lib/bindings/http/commons.js
- lib/bindings/http/emitter_binary.js
- lib/bindings/http/emitter_binary_0_1.js
- lib/bindings/http/emitter_structured.js
- lib/bindings/http/emitter_structured_0_1.js
- lib/bindings/http/receiver_binary.js
- lib/bindings/http/receiver_structured.js
- lib/bindings/http/receiver_structured_0_2.js
- lib/bindings/http/receiver_structured_0_3.js
- lib/bindings/http/receiver_structured_1.js
- lib/bindings/http/unmarshaller.js
- lib/bindings/http/unmarshaller_0_2.js
- lib/bindings/http/unmarshaller_0_3.js
- lib/cloudevent.js
- lib/formats/json/parser.js
- lib/specs/spec_0_1.js
- lib/specs/spec_0_2.js
- lib/specs/spec_0_3.js
- lib/specs/spec_1.js
> Use const instead of var where applicable

- lib/bindings/http/constants.js
With this protection in case some of this happen in some part of the code:
```js
// Leaving these in place for now. TODO: fixme
// eslint-disable-next-line
function checkDecorator(payload, headers) {
}
Constants.SPEC_V1 = "99";   <----------------------
// Leaving this in place for now. TODO: fixme
// eslint-disable-next-line
function Receiver(configuration) {
this.receiver = new BinaryHTTPReceiver(
parsersByEncoding,
setterByHeader,
allowedContentTypes,
requiredHeaders,
Spec,
Constants.SPEC_V1,
Constants.BINARY_HEADERS_1.EXTENSIONS_PREFIX,
checkDecorator
);
}
```
Then the tests and code will continue running without issues.
> fix: protects the consts from being changed in other parts of the code.

- lib/specs/spec_0_3.js
- lib/specs/spec_1.js
- package-lock.json
- package.json
- test/spec_0_3_tests.js
- test/spec_1_tests.js
> chore: Update uuid dependency

- .travis.yml
Signed-off-by: Helio Frota <00hf11@gmail.com>
> chore: Modify CI to also build backport branch(es)

- lib/bindings/http/unmarshaller.js
> lib: destruct contants in http/unmarshaller.js

- lib/validation_error.js
> lib: fix minor typo in ValidationError comment

- .github/workflows/codacy-coverage-reporter.yml
Using GitHub actions to run coverage reports.
> chore: add coverage GitHub action

- lib/cloudevent.js
- test/cloud_event_test.js
Fixes https://github.com/cloudevents/sdk-javascript/issues/191
> Initialize CloudEvent.extensions

- README.md
> docs(README): fix example typo

- webpack.config.js
the `_bundles/` was not ignored
> chore: add genertated _bundles to gitignore

- README.md
> docs(README): fix wrong order of arguments in the accept example

- LICENSE
Signed-off-by: Sidharth Vinod <sidharthv96@gmail.com>
> Add Copyright Date and Holder name

- src/event/spec.ts
- This commit removes two functions that are not used.
> lib: remove unused event creation functions

- package-lock.json
- package.json
> chore: move typedoc theme to a dev dependency.

- examples/websocket/index.html
- webpack.config.js
- This updates the browser based version to the name cloudevents.
- Fixes Issue #286 
- Version: 3.x
> fix: update browser name to cloudevents.

- src/index.ts
- src/transport/emitter.ts
- src/transport/index.ts
Fixes https://github.com/cloudevents/sdk-javascript/issues/272
> refactor: remove export star from transports

- src/index.ts
Some Small cleanup:
* The commented out version import now gets imported from the cloudevent.ts file
> chore: Remove commented version import.

- .gitignore
- package.json
- add cucumber.js to the list of files to be linted in package.json
- add /docs to .gitignore
> chore: add cucumber.js to list of files to lint and /docs to .gitignore

- .github/workflows/release-please.yml
> chore: update release please to the latest release(2.4.1)

- README.md
- Fix the sample code in README. There are some missing imports for `CloudEvent` objects
-
-
- Fixes Issue #
- Version:
> Fix minor import problems in README

- .github/workflows/nodejs-ci-action.yml
> chore: update CI workflow to include Node.js 14.x

- .github/pull-request-template.md
The existing template is a little meh.
> chore: tweak PR template

- package.json
Adding myself to the contributors list in package.json. I considered adding @lholmquist and @grant but then couldn't decide where to stop. Do I then add @danbev as well? Or @matejvasek or @aliok or whoever else has contributed in the past? Ultimately decided it was best to leave it up to the individual contributor. If you want to be listed in package.json just submit a PR.
> chore: add Lance Ball to maintainers in package.json

- src/message/http/index.ts
- src/message/index.ts
- src/transport/emitter.ts
Adds some additional JSDoc properties so the docs are clearer.
> doc: improve generated documentation

- .eslintrc
- cucumber.js
- package-lock.json
- package.json
- src/constants.ts
- src/event/cloudevent.ts
- src/event/interfaces.ts
- src/event/schemas.ts
- src/event/spec.ts
- src/event/validation.ts
- src/index.ts
- src/message/http/headers.ts
- src/message/http/index.ts
- src/message/index.ts
- src/parsers.ts
- src/transport/emitter.ts
- src/transport/http/index.ts
- src/transport/protocols.ts
- test/conformance/steps.ts
- test/integration/cloud_event_test.ts
- test/integration/constants_test.ts
- test/integration/emitter_factory_test.ts
- test/integration/emitter_singleton_test.ts
- test/integration/message_test.ts
- test/integration/parser_test.ts
- test/integration/sdk_test.ts
- test/integration/spec_03_tests.ts
- test/integration/spec_1_tests.ts
- test/integration/utilities_test.ts
Signed-off-by: Remi Cattiau <remi@cattiau.com>
Add lint rules for headers and add headers on all files
> chore: add copyrights header and lint rules

- examples/express-ex/index.js
> fix:  update express example with framework features.

- README.md
Normalizes the code example with the other samples in the README.
- Use correct syntax highlighting
- Use standard formatting
> docs: fix ts example

- package-lock.json
- package.json
This commit bumps uuid and superagent to the latest versions, and updates package-lock.json file to latest format.
> chore: update package.json format and deps

- package-lock.json
- package.json
> chore: bump webpack to 5.74.0

- package-lock.json
- package.json
> chore: Bump cucumber

- examples/mqtt-ex/README.md
- examples/mqtt-ex/package.json
- examples/mqtt-ex/src/index.ts
- examples/mqtt-ex/tsconfig.json
Added an example formatting MQTT messages and using the MQTT.js library to publish and suscribe from a MQTT server.
Fixes https://github.com/cloudevents/sdk-javascript/issues/464
> Add MQTT message protocol example

- .github/workflows/nodejs-ci-action.yml
- package-lock.json
- package.json
> feat!: remove Node 18 support
